spring:
  rabbitmq:
    addresses: localhost:5672
    username: user01
    password: user01
    virtual-host: vhost01
    listener:
      default-requeue-rejected: false
      acknowledge-mode: auto
      retry: 
        enabled: true

rabbitmq: 
  config:
    default-dead-letter-exchange-properties: 
      auto-delete: true
      durable: false
    dead-letter-exchange-postfix: .dlx  
    dead-letter-queue-postfix: .dlq 
    exchange: 
      cpm-cd-exchange: 
        name: cpm.cd.exchange-${user.name}
        type: direct
        durable: false
        auto-delete: true
      pil-deal-exchange: 
        name: pil.deal.exchange-${user.name}
        type: direct
        durable: false
        auto-delete: true 
      pil-deal-mock-exchange:
        name: pil.deal.mock.exchange-${user.name}
        type: direct
        durable: false
        auto-delete: true     
    queue: 
      cpm-cd-queue: 
        name: cpm.cd.queue-${user.name}
        durable: false
        auto-delete: true
        dead-letter-enabled: true
      pil-deal-queue: 
        name: pil.deal.queue-${user.name}
        durable: false
        auto-delete: true
        dead-letter-enabled: true  
      pil-deal-mock-queue: 
        name: pil.deal.mock.queue-${user.name}
        durable: false
        auto-delete: true
        dead-letter-enabled: false   
    binding: 
      cpm-cd-binding: 
        exchange: cpm-cd-exchange
        queue: cpm-cd-queue
        routing-key: cpm.cd.rkey
      pil-deal-binding: 
        exchange: pil-deal-exchange
        queue: pil-deal-queue
        routing-key: pil.deal.rkey
      pil-deal-mock-binding: 
        exchange: pil-deal-mock-exchange
        queue: pil-deal-mock-queue
        routing-key: pil.deal.mock.rkey        
        
      